version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-system-performance/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-system-performance/actions/workflows/test.yml)

  # Terraform ACI System Performance Module

  Manage ACI global System Performance setting 

  Location in GUI:
  'System' » 'System Settings' » 'System Performance'

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
